<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TraceCapsule.AspNetCore\TraceCapsule.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\TraceCapsule.OpenTelemetry\TraceCapsule.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\src\TraceCapsule.Http\TraceCapsule.Http.csproj" />
    <ProjectReference Include="..\..\src\TraceCapsule.RabbitMQ\TraceCapsule.RabbitMQ.csproj" />
  </ItemGroup>

</Project>
