<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TraceCapsule.RabbitMQ\TraceCapsule.RabbitMQ.csproj" />
    <ProjectReference Include="..\..\src\TraceCapsule.Cli\TraceCapsule.Cli.csproj" />
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.10" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TraceCapsule.AspNetCore\TraceCapsule.AspNetCore.csproj" />
    <ProjectReference Include="..\..\samples\SimpleApi\SimpleApi.csproj" />
    <ProjectReference Include="..\..\src\TraceCapsule.Core\TraceCapsule.Core.csproj" />
    <ProjectReference Include="..\..\src\TraceCapsule.OpenTelemetry\TraceCapsule.OpenTelemetry.csproj" />
    <ProjectReference Include="..\..\samples\DistributedTransferDemo\DistributedTransferDemo.csproj" />
  </ItemGroup>

</Project>
